# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f41112996684ccab82397c4c6f7915462d41c90b11cf2f0e80d7da742eed9e9c7c09ac02371fdc72ed647257d9a1321a67cd6c7a092af236dc988b6bf2478a93

test:
  secret_key_base: 67c6476f28d2904fd85886e592036cc2d5c44c2d7e35c12a669b7955719f7ef75c85c754131321d89c8bc7ac2531277e62f755e754eb58ed468cd2ee429757ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
